{% set version = "5.2" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: 8d399205578f1a9342816409cc1e46a93ebd5755e39ea2d85334bea911bf0e6e

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - pytz

test:
  imports:
    - tzlocal
  requires:
    - pip
  commands:
    - pip check

about:
  description: |
    This Python module returns a tzinfo object (with a pytz_deprecation_shim, 
    for pytz compatibility) with the local timezone information, 
    under Unix and Windows.
  doc_source_url: https://github.com/regebro/tzlocal/tree/{{ version }}
  home: https://github.com/regebro/tzlocal
  license: MIT 
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'tzinfo object for the local timezone'
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
