{% set version = "5.3.1" %}
{% set tests_to_skip = 'tests_to_skip + " or test_symlink_localtime or test_conflicting or test_noconflict"' %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: cceffc7edecefea1f595541dbd6e990cb1ea3d19bf01b2809f362a03dd7921fd

build:
  skip: true  # [py<39]
  number: 0
  script: python -m pip install --no-deps --ignore-installed . --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=64
  run:
    - python
    - backports.zoneinfo  # [py<39]
    - python-tzdata  # [win]
    - tzdata  # [win]

test:
  imports:
    - tzlocal
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    # Skipping tests due to a symlinks error
    # https://github.com/regebro/tzlocal/issues/146
    - pytest tests -vv -k "not ({{ tests_to_skip }})"

about:
  description: |
    This Python module returns a tzinfo object (with a pytz_deprecation_shim,
    for pytz compatibility) with the local timezone information,
    under Unix and Windows.
  doc_source_url: https://github.com/regebro/tzlocal/tree/{{ version }}
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: tzinfo object for the local timezone
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
