{% set version = "1.2.2" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8e7fb9f9301039c36fb0ff0a004ec36705ac46cee99a7373694a838adc8d30b0" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  fn: tzlocal-{{ version }}.tar.gz
  url: https://github.com/regebro/tzlocal/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytz

  run:
    - python
    - pytz

test:
  imports:
    - tzlocal

about:
  home: https://github.com/regebro/tzlocal
  license: CC0 1.0 Universal
  license: LICENSE.txt
  summary: 'tzinfo object for the local timezone'
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
