{% set name = "tzlocal" %}
{% set version = "1.4" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d3cdf502a4ae4b566abf948924e837b6c354aaed082eb1326c6c9043824cb4a7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: tzlocal-{{ version }}.tar.gz
  url: https://github.com/regebro/tzlocal/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pytz

test:
  imports:
    - tzlocal

about:
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_file: LICENSE.txt
  summary: 'tzinfo object for the local timezone'
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
