travis:
  secure:
    BINSTAR_TOKEN: feNJZGGIcHZW/CVsYBK0X/McR92xCtXvS4FC6sQyf+Nm+7p0iNkYXr2gfAqE4ozC0CaQYB42wsoO31RecBVcERS0tz2UH0fnJ+voijUilI05uMXdDgm2RMPe4MAaCmfapGXXr8NiFomg4MIzkRRKr8Yk5Ah8hL7/G282QHdfO8x40iAFdVradaZr/hlW0WyCGBy3IdBL3E5zuWaDoEeOol6y3DnShphZiM6ivCPdJZyGjTJua3St94Q5s80gVBzq4lQj66w44r/APMFlTVYw7s2lsczm24k41bz4R+VvxDgKItuUCooqxv19NBxw8mRxjWeH0m7ylIfBBs5MG5H+rdoSzj8luqXPp33NgKeREml75DLw7lceryj8ChAdvSzHDGlFne7yyCX2S4ctkd3asEE1TSs/nfPzGdB0RY0CSV7QavFn5Avl0VYrjaiuRd7nTUPb0jGpMJhtO3Biis33AcBPLV4MWLHVO99Y0TLXWLO1NAkOFiEX5XfHTb2Wm0lU3tfmT2j043btW5suqk0BL1llIu59VHnszkhhHbIvKhK5WPQ5IBm8F/KCeUfDSAte+dk1f9mdGB/L1P5pZokm9w8IC3RrNXxMLGSn66ZzsP0J7myaZLKJLP//4hp/BlYVMoFIa6jO+eg6pwIAqVrCadGBXOH3jaXndZzmYfQxdLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
