travis:
  secure:
    BINSTAR_TOKEN: bGE9H5WrTDFRbQrrv08o+3bDL2jzcv4MdI12XS2JzJfuEuM1KsPuGkv1uNXYksC0ykfoyKuoc7SvIdyim+Sk1tJVUB4IHYLINFjZ4ycfn7ar+6Ziu5rP1Hx2vY3usJ/5Q9s+lB7pa+OE7XJDS9WFercXNuqxSqZrAAlAdxWZPBGWhINt/92YshyMO6Olsn1jJgo5MEINKr0BEPyHnQwHb/dFnc6s4XtCeseEHuauvcnoUOe9aQ6Xb6/0NUvFY9ueSN6bmcg6bOVVi7iUfBCMc2Xan+34a7q3ZvXN8UljeEE4LK8Z1RHDZbVMB9kvArllxoabaI53kCCJijyBKAFqY2iMxgcYu3uipuw/OCNYHy+DsdRUIe+LGNpogtjkCDO7lWBVc1COBpY5aYe9gA4w+m/V9CldKsnO9m5BqYKhU77RXcUme9QxE8zD9OYCt4jZVKjOkh5dqJUKCn1hXfKwtW2WP1nzjNSR05BgENWpospLTHNGEvMEXadSWBGbL8F0I7PSAJ6tzl4/EaQ0XzrPZWGTrFXKbPqWuZwdS4OYGJTIXKKs8J7Ham6j39dqc14yxqO5zll2Uy/YBpGSchd2cvo/XKVUhjI1B3M8Jy1Ww0SJUOC4yUY6l8a+q23+6ZnQGEJn/KBCIY8krKzwrK/GnPXrmpK9rrwXYWJt02dTI2M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
