travis:
  secure:
    BINSTAR_TOKEN: ZcQBS9nd1u8JYysvRIXukDdveBAAPc1x7/hrJtIfu+CY8xQJ60otJ0r41Md45RAWbR7SY3wZFXIgMYLTrvTb99iVsZfoGRrv86yBL6+hHUvDjdm8H/c07q99DzvynNkM/ISxI3oJK0hbltF/bQZUiJvj4U9NLv8s7AyLYcX4ASPDjJZKrzeikpf6ik1unnzLMz+Y+684Dm6KdqWcBVkNKe401VGHtSdSbbRxZvSm5lCEkoLRz1OAbo7iJMduLwGFc+zfoSUlWOO228dPtVJbwKhjK1v6ocS3BN4i25tIaWwFzSfyAePzWTK0/6gLZEyaDeSeqP+Cxnud9aCfTrv+Ocoho+0Rv+RzCMsf6S5qoy0ZxcDMhLpCJhW0B71uR8nVfhV3mfCLyxRFmpYpPptVRIiNq03cGztvmwxopl09iUHjYfOqHeJN16NETWwW3d3btnRGPMnJGo62k+yMaLZC7n/ie19MpexB6tOY9KLqv5qNX1Vii2zBvCilB6JCDcqe4iCTzPSTwh10XRr9BgnS9j+TvRvSVTun5GVOJ7MsTaToWyJ4o7A2c+kytOxqgZA73qID+SBjjr7wS6ZvZ9KcD5ufTRElTumbtou5qBxqAK1tpxOU2tfVEYVhPRX6gTSfddpPS304Q9bvzTnXOU9iH/Gp12eX6NNpZjbtum2VKaE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
