travis:
  secure:
    BINSTAR_TOKEN: iMEk5UDZa/dWJ4ZNp5hYjAHax25FSCsnSrSkyojlHJnnsQPczHCUJ+rpmioyrmBM/wUAY2rmtkrDfsgs8OSSPsgXkh01V2WK7CGBDon3iQlB+FhOJFax8cmnXvGBcID2eOrPMPBsGoMTS4Cxn+F5PUIlOefs4B3tdupCm6fERM7NZPXVgnwpB6NX+nU4ub07RfmG/7l/9+Qn8UZpVd4FTg8c/fOgcdSZiwWeksMwO0o+GiRcVEWm3Y6C+fAH5XVeu/hoHgZA3kzmVaJd9/2q22OlKkDsaaQFEg7+OGu6udztqmOYv5vYGWbxXdo2+8udCWMYR15XwGlvY90DU9yx9LkcoT0LNHdDPp/3DkKXU+pZYJ0l8048JNrlN8C8Ly/omdEK9m7n0jzjfknPG77gB8PhoAeESqHDqtiU3+tRvszxNWIFF/GVPC5UChx/1EXLipdh9yV/kYSYDXuG+Sdzj5HVo154CLTpcyhsz/b0QH54uIKrSEOjV421Jfj6c/zm8gad+F5QuzdqbPXo8SxlkOkdcB+fh2e7jJ3qzVyFMaFbC6/s1QinEvi3IvE0VBKl59dhCdK99hECtejVhGn79vYfDEsrFlwQcZUDw80yyGNA8oyrL5fjl3mJmdNCOpLy/mJy2p/F8ZDs4+Zk6XqUYgQ0o+Cp9EvmIwXVhMZQmFg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
